### ISSUE TITLE
Name the game states and create a flowchart

### ISSUE THREAD

**Issue by Velfi** [Velfi/trans-code-game#10]
# Situation 

# Target 

# Proposal

**Comment by approximatelylinear** [comment]
```
blockdiag {
  Start [label = "Start", shape = circle]
  CharCreation [label = "Character Creation"]
  Cutscene [label = "Cutscene Exposition"]
  Tutorial [label = "Quick Tutorial"]
  Game [label = "Game"]
  Pause [label = "Pause Screen"]
  Win [label = "Win", shape = circle]
  Lose [label = "Lose", shape = circle]

  Start -> CharCreation -> Cutscene
  Cutscene -> Tutorial
  Cutscene -> Game
  Tutorial -> Game
  Game -> Pause
  Game -> Win
  Game -> Lose
  Pause -> Game
  Win -> CharCreation [label="Choose New Clothes", textcolor="green"]
  Game -> Lose [label="Try Again", textcolor="red"]
}
```
[Interactive block diagram editor](http://interactive.blockdiag.com/?compression=deflate&src=eJxtkcFqwzAMhu97CpFz9wgZlDB2GWOjhR3KDqorElOvKrLCOsbefbazuGrp8f_1S9YnbwO7_c5jDz93ACtFUdgE3FKAFpqimwXEAY-UDOfFBfpIyW5A6YRQPR9MQ7bRKQnMxaakR42ODmSTs_V4OnL0NboelcVjMNG30bt9LZTUE37aYVkW_xXHaAuTXjkhmsa_e7tuUjfpnvliSpY3cvVg9w-X98j6H8_CJ3uGuLLz_pb9bBXQJAuI0Wlzo_KClf7cnGGvd5uo2vRTnCFf6Au6wDpQTIRKJ3UcWNqmryezj9T2tXzDssdyP9MltEs9v39WYr0O)
