### ISSUE TITLE
Design avatar base

### ISSUE THREAD

**Issue by kmorsebrown** [Velfi/trans-code-game#16]
# Situation

Interacting with an avatar will be a key component of our game. 

*TBD*: Describe possible interactions

# Target

Human-based avatar
    - Hair
    - Eyes
    - Skin color
    - Body shape
    - Position / Posture (?)

# Proposal

**Comment by approximatelylinear** [comment]
Assets!

* [Drawing 1](https://assets.adobe.com/link/07ac8b75-4259-4d37-7597-05b2c09038d3)
* [Head](https://assets.adobe.com/link/67323f8d-93c5-4d7e-60c0-2739e9b0fc2d)
* [TC Icons](https://assets.adobe.com/link/5c90e087-e6bf-4067-62f7-9d274c2354ba)
* [Shirts](https://assets.adobe.com/link/3420c4c5-b228-4212-6f6b-be0b8c71cfe3)
* [Shoes](https://assets.adobe.com/link/3c0c5eea-33cc-44ca-5866-3647dd7516f8)
* [TC Timer bar](https://assets.adobe.com/link/548b3d22-68d9-4695-4cf8-f40829da6911)
