### ISSUE TITLE
Game story and cut scenes

### ISSUE THREAD

**Issue by Quinn-D** [Velfi/trans-code-game#22]
Generate the cut scenes, and assembled into story

**Comment by approximatelylinear** [comment]
Hey @Quinn-D ! Can you drop a link to where the cut scenes are located? Are they in the code?

**Comment by Quinn-D** [comment]
https://github.com/Velfi/trans-code-game/wiki/Story%20Flow

**Comment by Quinn-D** [comment]
There was not yet a location to put them, so they are sitting on the wiki.  A data structure is there to copy and paste in.
