### ISSUE TITLE
Site base styling.

### ISSUE THREAD

**Issue by Velfi** [Velfi/trans-code-game#5]
# Situation
Starting from scratch... 

# Target
Create styles in css for the site.

- Colors
    - See #11 
- Fonts 
    - Title
    - Body
    - Game-internal text

# Proposal

- Colors: See #11

- Fonts 
    - Title: *TBD*
    - Body: *TBD*
    - Game-internal text: * TBD

**Comment by stephmarx** [comment]
Everything external to canvas - title, center canvas, etc
