### ISSUE TITLE
Create Javascript development environment

### ISSUE THREAD

**Issue by approximatelylinear** [Velfi/trans-code-game#6]
# Situation

Decide on standard Javascript conventions, libraries and build process

# Target 

## Conventions

- Javascript version
    - ES5
    - ES6

- Style guide
        - ~[Airbnb Style Guide](https://github.com/airbnb/javascript)~
        - [Google Style Guide](https://google.github.io/styleguide/jsguide.html)

- Testing 
    
- Styling

## Libraries

- Game engine
    - [Phaser](https://phaser.io/)
- Generic Framework 
    - [React](https://facebook.github.io/react/)
- Styling
    - SASS

## Build process
- Build tool
    - [Gulp](http://gulpjs.com/)
    - [Webpack](webpack.github.io)
- Deployment targets
    - Local machine
    - Elastic beanstalk (See #3 )

# Proposal 

## Conventions

- Javascript version: TBD

- Style guide: [Google Style Guide](https://google.github.io/styleguide/jsguide.html) (per @korey-enright)

- Testing: TBD 

- Styling: TBD

-

**Comment by korey-enright** [comment]
I pretty strongly prefer the Google style guide version of JS
